%define svnver 20101107-051001
%define svnrev 514
%define origname motion

Name: %{origname}-svn
Version: 3.2.12
Release: %mkrel 1
Summary: Video surveilance system (motion detector)
License: GPL
Group: Video
URL: https://www.lavrsen.dk/foswiki/bin/view/Motion/WebHome
Source: http://www.lavrsen.dk/sources/motion-daily/%{origname}-%{svnver}.tar.gz
Source1: %{origname}.init
Requires: libjpeg libffmpeg
BuildRequires: libjpeg-devel libffmpeg-devel mysql-devel
BuildRoot: %{_tmppath}/%{name}-%{version}-%{release}-root

%description
Motion is a software motion detector. It grabs images from video4linux
devices and/or from webcams (such as the axis network cameras). Motion
is the perfect tool for keeping an eye on your property keeping only
those images that are interesting. Motion is strictly command line
driven and can run as a daemon with a rather small footprint. It is
built with MySQL and mpegs generated by ffmpeg and http remote control.

%prep
%setup -q -n %{origname}-%{svnver}
perl -pi -w -e 's/trunkREV%{svnrev}/3.2.12/' ./configure
perl -pi -w -e 's/trunk-r%{svnrev}/3.2.12/' ./configure

%build
%configure --sysconfdir=/etc/%{origname} --with-linuxthreads --without-pgsql
%make

%install
rm -rf %{buildroot}
%makeinstall_std
mkdir -p %{buildroot}/%{_initrddir}
install -m 755 %{SOURCE1} %{buildroot}/%{_initrddir}/%{origname}
mv %{buildroot}%{_sysconfdir}/%{origname}/motion-dist.conf %{buildroot}%{_sysconfdir}/%{origname}/%{origname}.conf
mkdir -p %{buildroot}%{_var}/run/motion
chmod a+rwt %{buildroot}%{_var}/run/motion

%clean
rm -rf %{buildroot}

%post
%_post_service %{origname}

%preun
%_preun_service %{origname}

%files
%defattr(-,root,root)
%doc FAQ CHANGELOG COPYING CREDITS INSTALL README README.axis_2100 motion_guide.html
%dir /usr/share/doc/%{origname}-%{version}
%dir /usr/share/%{origname}-%{version}
%config(noreplace) %{_sysconfdir}/%{origname}/%{origname}.conf
%{_bindir}/%{origname}
%{_initrddir}/%{origname}
%{_mandir}/man*/%{origname}.*
%{_datadir}/doc/%{origname}-%{version}/*
%{_datadir}/%{origname}-%{version}/*
%{_var}/run/motion
